name: Report an issue with rtl_433 Home Assistant add-ons
description: Report an issue with the Home Assistant add-on itself.
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only!

        Before reporting a bug, please check:

        1. Add `output kv` to your `rtl433` configuration file and confirm messages are being captured.
        2. Check that messages are being sent to your MQTT broker using a tool such as [MQTT Explorer](https://mqtt-explorer.com).

  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing here, to communicate to the
        maintainers. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: dropdown
    validations:
      required: true
    attributes:
      label: What addon are you reporting the bug for?
      description: >
        Are you experiencing a bug with rtl_433 or rtl_433_mqtt_autodiscovery?
      options:
        - rtl_443
        - rtl_433_mqtt_autodiscover
  - type: input
    attributes:
      label: What is the addon version?
      placeholder: 0.2.3
    validations:
      required: true
  - type: dropdown
    validations:
      required: true
    attributes:
      label: What type of MQTT Broker are you using?
      description: >
        Are you using the Home Assistant Mosquitto addon or something else?
      options:
        - Home Assistant Mosquitto MQTT Broker
        - Other (details in the bug description)

  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    attributes:
      label: Addon log messages
      placeholder: "Copy and paste the addon log here"
      description: >-
        rtl_433 logs can be found in: [Settings -> Add-ons -> rtl_433](https://my.home-assistant.io/redirect/supervisor_addon/?addon=9b13b3f4_rtl433).
        rtl_433_mqtt_autodiscovery logs can be found in: [Settings -> Add-ons -> rtl_433](https://my.home-assistant.io/redirect/supervisor_addon/?addon=9b13b3f4_rtl433mqttautodiscovery).
      render: txt
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
