build_from:
  aarch64: homeassistant/aarch64
  amd64: homeassistant/amd64-base
  armhf: homeassistant/armhf-base
  armv7: homeassistant/armv7-base
  i386: homeassistant/i386-base
args:
  rtl433GitRevision: master
