name: rtl_433
image: ghcr.io/catduckgnaf/rtl_433-haos-addon-rtl_433-{arch}
version: 0.2.5
slug: rtl433
description: Receive wireless sensor data via an SDR dongle and rtl_433
url: https://github.com/catduckgnaf/rtl_433_haos_addon/tree/main/rtl_433
arch:
- armhf
- armv7
- aarch64
- amd64
- i386
init: false
map:
- config:rw
- share:rw
services:
- mqtt:want
usb: true
udev: true
options:
  retain: true
schema:
  retain: bool
