name: rtl_433
image: ghcr.io/catduckgnaf/rtl_433_haos_addon-rtl_433-{arch}
version: 0.2.7
slug: rtl433
description: Receive wireless sensor data via an SDR dongle and rtl_433
url: https://github.com/catduckgnaf/rtl_433_haos_addon/tree/main/rtl_433
arch:
- armhf
- armv7
- aarch64
- amd64
- i386
init: false
map:
- config:rw
- share:rw
services:
- mqtt:want
usb: true
udev: true
options:
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  retain: false
  rtl_topic: "rtl_433/+/events"
  discovery_prefix: "homeassistant"
  discovery_interval: 600
  log_level: "default"
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str
  retain: bool
  rtl_topic: str
  discovery_prefix: str
  discovery_interval: int
  log_level: list(default|quiet|debug)

